//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyZoo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyZoo.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animal.
        /// </summary>
        internal static string addAnimalWindowTitle {
            get {
                return ResourceManager.GetString("addAnimalWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age cannot be negative!.
        /// </summary>
        internal static string ageIsNegativeError {
            get {
                return ResourceManager.GetString("ageIsNegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be less then .
        /// </summary>
        internal static string ageMustBeLessThenError {
            get {
                return ResourceManager.GetString("ageMustBeLessThenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal.
        /// </summary>
        internal static string animalElementXml {
            get {
                return ResourceManager.GetString("animalElementXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is too long!.
        /// </summary>
        internal static string animalNameIsTooLongError {
            get {
                return ResourceManager.GetString("animalNameIsTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is too short!.
        /// </summary>
        internal static string animalNameIsTooShortError {
            get {
                return ResourceManager.GetString("animalNameIsTooShortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal type not supported..
        /// </summary>
        internal static string animalTypeNotSupportedError {
            get {
                return ResourceManager.GetString("animalTypeNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This animal walks freely.
        /// </summary>
        internal static string animalWalksFreely {
            get {
                return ResourceManager.GetString("animalWalksFreely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ate {0}..
        /// </summary>
        internal static string ate {
            get {
                return ResourceManager.GetString("ate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ate {0} and now {1}..
        /// </summary>
        internal static string ateWithConsequence {
            get {
                return ResourceManager.GetString("ateWithConsequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is dissatisfied.
        /// </summary>
        internal static string consequenceDissatisfied {
            get {
                return ResourceManager.GetString("consequenceDissatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feels bad.
        /// </summary>
        internal static string consequenceFeelsBad {
            get {
                return ResourceManager.GetString("consequenceFeelsBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wants more.
        /// </summary>
        internal static string consequenceWantsMore {
            get {
                return ResourceManager.GetString("consequenceWantsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hided into water..
        /// </summary>
        internal static string crocodileDefaultCrazyAction {
            get {
                return ResourceManager.GetString("crocodileDefaultCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just crocodile. Don&apos;t put your hands to her..
        /// </summary>
        internal static string crocodileDescription {
            get {
                return ResourceManager.GetString("crocodileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is indifferent to {0}..
        /// </summary>
        internal static string crocodileIndifferentAction {
            get {
                return ResourceManager.GetString("crocodileIndifferentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is interested in new zoo inhabitant {0}..
        /// </summary>
        internal static string crocodileInterestedAction {
            get {
                return ResourceManager.GetString("crocodileInterestedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandy.
        /// </summary>
        internal static string crocodileName {
            get {
                return ResourceManager.GetString("crocodileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;zzz...&quot;.
        /// </summary>
        internal static string crocodileOnAnimalJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("crocodileOnAnimalJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is swimming to become friends with {0}..
        /// </summary>
        internal static string crocodileOnCrocodileJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("crocodileOnCrocodileJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        internal static string crocodilePreferableFood {
            get {
                return ResourceManager.GetString("crocodilePreferableFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string crocodileSound {
            get {
                return ResourceManager.GetString("crocodileSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is {0}, he or she is {1} years old..
        /// </summary>
        internal static string describeDefault {
            get {
                return ResourceManager.GetString("describeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields cannot be empty.
        /// </summary>
        internal static string emptyFieldsError {
            get {
                return ResourceManager.GetString("emptyFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string emptyListJson {
            get {
                return ResourceManager.GetString("emptyListJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only digits.
        /// </summary>
        internal static string enterDigitsError {
            get {
                return ResourceManager.GetString("enterDigitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only letters.
        /// </summary>
        internal static string enterLettersError {
            get {
                return ResourceManager.GetString("enterLettersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs.json.
        /// </summary>
        internal static string filenameLogJson {
            get {
                return ResourceManager.GetString("filenameLogJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs.xml.
        /// </summary>
        internal static string filenameLogXml {
            get {
                return ResourceManager.GetString("filenameLogXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food cannot be empty string.
        /// </summary>
        internal static string foodEmptyStringError {
            get {
                return ResourceManager.GetString("foodEmptyStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest.
        /// </summary>
        internal static string forestVoljeerName {
            get {
                return ResourceManager.GetString("forestVoljeerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At night {0} becomes fast as Sonic and runs all over the place..
        /// </summary>
        internal static string hedgehogCrazyAction {
            get {
                return ResourceManager.GetString("hedgehogCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snake.
        /// </summary>
        internal static string hedgehogPreferableFood {
            get {
                return ResourceManager.GetString("hedgehogPreferableFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to squeaky-squeak.
        /// </summary>
        internal static string hedgehogSound {
            get {
                return ResourceManager.GetString("hedgehogSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The horse rears and thrashes wildly..
        /// </summary>
        internal static string horseCrazyAction {
            get {
                return ResourceManager.GetString("horseCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b(apple|sugar|oat)\b.
        /// </summary>
        internal static string horseCrazyFoodPattern {
            get {
                return ResourceManager.GetString("horseCrazyFoodPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carrots.
        /// </summary>
        internal static string horsePreferableFood {
            get {
                return ResourceManager.GetString("horsePreferableFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eeehh-heee-heeeh.
        /// </summary>
        internal static string horseSound {
            get {
                return ResourceManager.GetString("horseSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct values.
        /// </summary>
        internal static string incorrectValuesError {
            get {
                return ResourceManager.GetString("incorrectValuesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string informationElementXml {
            get {
                return ResourceManager.GetString("informationElementXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is eating {0} - progress {1}.
        /// </summary>
        internal static string isEating {
            get {
                return ResourceManager.GetString("isEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z\s]+$.
        /// </summary>
        internal static string isLetterRegex {
            get {
                return ResourceManager.GetString("isLetterRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kivi transforms into the kivi fruit..
        /// </summary>
        internal static string kiwiCrazyAction {
            get {
                return ResourceManager.GetString("kiwiCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kiwi.
        /// </summary>
        internal static string kiwiPreferableFood {
            get {
                return ResourceManager.GetString("kiwiPreferableFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kee-wee, kee-wee, kee-wee.
        /// </summary>
        internal static string kiwiSound {
            get {
                return ResourceManager.GetString("kiwiSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haven&apos;t been fed for {0} seconds, now is feeling fresh and playing with a ball as a kitten..
        /// </summary>
        internal static string lionCrazyAction {
            get {
                return ResourceManager.GetString("lionCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes to eat and sleep..
        /// </summary>
        internal static string lionDescription {
            get {
                return ResourceManager.GetString("lionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simba.
        /// </summary>
        internal static string lionName {
            get {
                return ResourceManager.GetString("lionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not interested in {0} and continue basking in the sun..
        /// </summary>
        internal static string lionOnAnimalJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("lionOnAnimalJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doesn&apos;t stand {0} on his territory..
        /// </summary>
        internal static string lionOnLionJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("lionOnLionJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is sure it was better without {0}..
        /// </summary>
        internal static string lionOnMonkeyJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("lionOnMonkeyJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is figuring out how to eat {0}..
        /// </summary>
        internal static string lionOnZebraJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("lionOnZebraJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat.
        /// </summary>
        internal static string lionPreferableFood {
            get {
                return ResourceManager.GetString("lionPreferableFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrr!.
        /// </summary>
        internal static string lionSound {
            get {
                return ResourceManager.GetString("lionSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string logElementXml {
            get {
                return ResourceManager.GetString("logElementXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runs around the enclosure like crazy..
        /// </summary>
        internal static string monkeyDefaultCrazyAction {
            get {
                return ResourceManager.GetString("monkeyDefaultCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throws bananas to public..
        /// </summary>
        internal static string monkeyDescription {
            get {
                return ResourceManager.GetString("monkeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to throws {0} back..
        /// </summary>
        internal static string monkeyFoodCrazyAction {
            get {
                return ResourceManager.GetString("monkeyFoodCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to George.
        /// </summary>
        internal static string monkeyName {
            get {
                return ResourceManager.GetString("monkeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is throwing a coconut at {0}..
        /// </summary>
        internal static string monkeyOnAnimalJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("monkeyOnAnimalJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit.
        /// </summary>
        internal static string monkeyPreferableFood {
            get {
                return ResourceManager.GetString("monkeyPreferableFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uga! Uga!.
        /// </summary>
        internal static string monkeySound {
            get {
                return ResourceManager.GetString("monkeySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana.
        /// </summary>
        internal static string monkeyTriggerFood {
            get {
                return ResourceManager.GetString("monkeyTriggerFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now {0} and shares this wisdom with you - {1}.
        /// </summary>
        internal static string owlCrazyAction {
            get {
                return ResourceManager.GetString("owlCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hoo.
        /// </summary>
        internal static string owlCrazyActionTrigger {
            get {
                return ResourceManager.GetString("owlCrazyActionTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old and wise owl..
        /// </summary>
        internal static string owlDescription {
            get {
                return ResourceManager.GetString("owlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedwig.
        /// </summary>
        internal static string owlName {
            get {
                return ResourceManager.GetString("owlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sir {0}.
        /// </summary>
        internal static string owlNewAnimalName {
            get {
                return ResourceManager.GetString("owlNewAnimalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is knighting {0}. The zoo will hear of {1}&apos;s glorious deeds!.
        /// </summary>
        internal static string owlOnAnimalJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("owlOnAnimalJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        internal static string owlPreferableFood {
            get {
                return ResourceManager.GetString("owlPreferableFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoo hoo..
        /// </summary>
        internal static string owlSound {
            get {
                return ResourceManager.GetString("owlSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owls rotate heads nearly 270°..
        /// </summary>
        internal static string owlWisdom1 {
            get {
                return ResourceManager.GetString("owlWisdom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of special feathers structure to fly silently, owls easily go wet..
        /// </summary>
        internal static string owlWisdom2 {
            get {
                return ResourceManager.GetString("owlWisdom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best pet? Definitely a snake!.
        /// </summary>
        internal static string owlWisdom3 {
            get {
                return ResourceManager.GetString("owlWisdom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asymmetrical ears help owls catch crazy zoo gossip..
        /// </summary>
        internal static string owlWisdom4 {
            get {
                return ResourceManager.GetString("owlWisdom4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owls don’t build nests - they just move in..
        /// </summary>
        internal static string owlWisdom5 {
            get {
                return ResourceManager.GetString("owlWisdom5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        internal static string pathBack {
            get {
                return ResourceManager.GetString("pathBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▒.
        /// </summary>
        internal static string progressBarEmptyElement {
            get {
                return ResourceManager.GetString("progressBarEmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to █.
        /// </summary>
        internal static string progressBarFilledElement {
            get {
                return ResourceManager.GetString("progressBarFilledElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string rootElementXml {
            get {
                return ResourceManager.GetString("rootElementXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savanna.
        /// </summary>
        internal static string savannaVoljeerName {
            get {
                return ResourceManager.GetString("savannaVoljeerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s: {1} (avg {2} ages).
        /// </summary>
        internal static string statisticsRecord {
            get {
                return ResourceManager.GetString("statisticsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The largest voljeer - {0}.
        /// </summary>
        internal static string statisticsRecordLargestVoljeer {
            get {
                return ResourceManager.GetString("statisticsRecordLargestVoljeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The oldest - {0} {1} ({2}).
        /// </summary>
        internal static string statisticsRecordOldest {
            get {
                return ResourceManager.GetString("statisticsRecordOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string timestampElementXml {
            get {
                return ResourceManager.GetString("timestampElementXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropics.
        /// </summary>
        internal static string tropicsVoljeerName {
            get {
                return ResourceManager.GetString("tropicsVoljeerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now full of energy, runs around and bucks..
        /// </summary>
        internal static string zebraCrazyAction {
            get {
                return ResourceManager.GetString("zebraCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was born in savanna and moved to the zoo at 1 year old. Sometimes bites..
        /// </summary>
        internal static string zebraDescription {
            get {
                return ResourceManager.GetString("zebraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doesn&apos;t want more food; {0} {1}.
        /// </summary>
        internal static string zebraIsFull {
            get {
                return ResourceManager.GetString("zebraIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marty.
        /// </summary>
        internal static string zebraName {
            get {
                return ResourceManager.GetString("zebraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not sure it is a good idea to become friends with {0}..
        /// </summary>
        internal static string zebraOnAnimalJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("zebraOnAnimalJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is showing flower to {0}..
        /// </summary>
        internal static string zebraOnZebraJoinedInSameEnclosureAction {
            get {
                return ResourceManager.GetString("zebraOnZebraJoinedInSameEnclosureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        internal static string zebraPreferableFood {
            get {
                return ResourceManager.GetString("zebraPreferableFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hufff..
        /// </summary>
        internal static string zebraSound {
            get {
                return ResourceManager.GetString("zebraSound", resourceCulture);
            }
        }
    }
}
